// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rulsif_solve_cpp
arma::vec rulsif_solve_cpp(const arma::mat& H, const arma::vec& h, double lambda);
RcppExport SEXP _kernR_rulsif_solve_cpp(SEXP HSEXP, SEXP hSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type H(HSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(rulsif_solve_cpp(H, h, lambda));
    return rcpp_result_gen;
END_RCPP
}
// hsic_stat_cpp
double hsic_stat_cpp(const arma::mat& Kx, const arma::mat& Ky);
RcppExport SEXP _kernR_hsic_stat_cpp(SEXP KxSEXP, SEXP KySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Kx(KxSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Ky(KySEXP);
    rcpp_result_gen = Rcpp::wrap(hsic_stat_cpp(Kx, Ky));
    return rcpp_result_gen;
END_RCPP
}
// weighted_hsic_stat_cpp
double weighted_hsic_stat_cpp(const arma::mat& Kx, const arma::mat& Ky, const arma::vec& w);
RcppExport SEXP _kernR_weighted_hsic_stat_cpp(SEXP KxSEXP, SEXP KySEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Kx(KxSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Ky(KySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(weighted_hsic_stat_cpp(Kx, Ky, w));
    return rcpp_result_gen;
END_RCPP
}
// median_bandwidth_cpp
double median_bandwidth_cpp(const arma::mat& x);
RcppExport SEXP _kernR_median_bandwidth_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(median_bandwidth_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// rbf_kernel_matrix_cpp
arma::mat rbf_kernel_matrix_cpp(const arma::mat& x, const arma::mat& y, double bandwidth);
RcppExport SEXP _kernR_rbf_kernel_matrix_cpp(SEXP xSEXP, SEXP ySEXP, SEXP bandwidthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type bandwidth(bandwidthSEXP);
    rcpp_result_gen = Rcpp::wrap(rbf_kernel_matrix_cpp(x, y, bandwidth));
    return rcpp_result_gen;
END_RCPP
}
// matern_kernel_matrix_cpp
arma::mat matern_kernel_matrix_cpp(const arma::mat& x, const arma::mat& y, double bandwidth, double nu);
RcppExport SEXP _kernR_matern_kernel_matrix_cpp(SEXP xSEXP, SEXP ySEXP, SEXP bandwidthSEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type bandwidth(bandwidthSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(matern_kernel_matrix_cpp(x, y, bandwidth, nu));
    return rcpp_result_gen;
END_RCPP
}
// linear_kernel_matrix_cpp
arma::mat linear_kernel_matrix_cpp(const arma::mat& x, const arma::mat& y);
RcppExport SEXP _kernR_linear_kernel_matrix_cpp(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(linear_kernel_matrix_cpp(x, y));
    return rcpp_result_gen;
END_RCPP
}
// polynomial_kernel_matrix_cpp
arma::mat polynomial_kernel_matrix_cpp(const arma::mat& x, const arma::mat& y, int degree, double offset);
RcppExport SEXP _kernR_polynomial_kernel_matrix_cpp(SEXP xSEXP, SEXP ySEXP, SEXP degreeSEXP, SEXP offsetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type degree(degreeSEXP);
    Rcpp::traits::input_parameter< double >::type offset(offsetSEXP);
    rcpp_result_gen = Rcpp::wrap(polynomial_kernel_matrix_cpp(x, y, degree, offset));
    return rcpp_result_gen;
END_RCPP
}
// mmd2_unbiased_cpp
double mmd2_unbiased_cpp(const arma::mat& Kxx, const arma::mat& Kyy, const arma::mat& Kxy);
RcppExport SEXP _kernR_mmd2_unbiased_cpp(SEXP KxxSEXP, SEXP KyySEXP, SEXP KxySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Kxx(KxxSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Kyy(KyySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Kxy(KxySEXP);
    rcpp_result_gen = Rcpp::wrap(mmd2_unbiased_cpp(Kxx, Kyy, Kxy));
    return rcpp_result_gen;
END_RCPP
}
// mmd2_biased_cpp
double mmd2_biased_cpp(const arma::mat& Kxx, const arma::mat& Kyy, const arma::mat& Kxy);
RcppExport SEXP _kernR_mmd2_biased_cpp(SEXP KxxSEXP, SEXP KyySEXP, SEXP KxySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Kxx(KxxSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Kyy(KyySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Kxy(KxySEXP);
    rcpp_result_gen = Rcpp::wrap(mmd2_biased_cpp(Kxx, Kyy, Kxy));
    return rcpp_result_gen;
END_RCPP
}
// permutation_hsic_cpp
arma::vec permutation_hsic_cpp(const arma::mat& Kx, const arma::mat& Ky, int n_perm);
RcppExport SEXP _kernR_permutation_hsic_cpp(SEXP KxSEXP, SEXP KySEXP, SEXP n_permSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Kx(KxSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Ky(KySEXP);
    Rcpp::traits::input_parameter< int >::type n_perm(n_permSEXP);
    rcpp_result_gen = Rcpp::wrap(permutation_hsic_cpp(Kx, Ky, n_perm));
    return rcpp_result_gen;
END_RCPP
}
// permutation_mmd_cpp
arma::vec permutation_mmd_cpp(const arma::mat& K_pool, int n, int m, int n_perm);
RcppExport SEXP _kernR_permutation_mmd_cpp(SEXP K_poolSEXP, SEXP nSEXP, SEXP mSEXP, SEXP n_permSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type K_pool(K_poolSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type n_perm(n_permSEXP);
    rcpp_result_gen = Rcpp::wrap(permutation_mmd_cpp(K_pool, n, m, n_perm));
    return rcpp_result_gen;
END_RCPP
}
// stratified_permute_cpp
arma::uvec stratified_permute_cpp(const arma::ivec& bins, int n_bins);
RcppExport SEXP _kernR_stratified_permute_cpp(SEXP binsSEXP, SEXP n_binsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::ivec& >::type bins(binsSEXP);
    Rcpp::traits::input_parameter< int >::type n_bins(n_binsSEXP);
    rcpp_result_gen = Rcpp::wrap(stratified_permute_cpp(bins, n_bins));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_kernR_rulsif_solve_cpp", (DL_FUNC) &_kernR_rulsif_solve_cpp, 3},
    {"_kernR_hsic_stat_cpp", (DL_FUNC) &_kernR_hsic_stat_cpp, 2},
    {"_kernR_weighted_hsic_stat_cpp", (DL_FUNC) &_kernR_weighted_hsic_stat_cpp, 3},
    {"_kernR_median_bandwidth_cpp", (DL_FUNC) &_kernR_median_bandwidth_cpp, 1},
    {"_kernR_rbf_kernel_matrix_cpp", (DL_FUNC) &_kernR_rbf_kernel_matrix_cpp, 3},
    {"_kernR_matern_kernel_matrix_cpp", (DL_FUNC) &_kernR_matern_kernel_matrix_cpp, 4},
    {"_kernR_linear_kernel_matrix_cpp", (DL_FUNC) &_kernR_linear_kernel_matrix_cpp, 2},
    {"_kernR_polynomial_kernel_matrix_cpp", (DL_FUNC) &_kernR_polynomial_kernel_matrix_cpp, 4},
    {"_kernR_mmd2_unbiased_cpp", (DL_FUNC) &_kernR_mmd2_unbiased_cpp, 3},
    {"_kernR_mmd2_biased_cpp", (DL_FUNC) &_kernR_mmd2_biased_cpp, 3},
    {"_kernR_permutation_hsic_cpp", (DL_FUNC) &_kernR_permutation_hsic_cpp, 3},
    {"_kernR_permutation_mmd_cpp", (DL_FUNC) &_kernR_permutation_mmd_cpp, 4},
    {"_kernR_stratified_permute_cpp", (DL_FUNC) &_kernR_stratified_permute_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_kernR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
