# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' RuLSIF kernel density ratio estimation (core solver)
#'
#' Solves the RuLSIF optimisation
#' \deqn{\theta = (H + \lambda I)^{-1} h}{theta = (H + lambda*I)^(-1) h}
#' with non-negativity constraint (clamp negatives to 0).
#'
#' @param H Gram matrix (n_basis x n_basis).
#' @param h Mean kernel vector (n_basis).
#' @param lambda Regularisation parameter.
#' @return Coefficient vector theta.
#' @keywords internal
rulsif_solve_cpp <- function(H, h, lambda) {
    .Call(`_kernR_rulsif_solve_cpp`, H, h, lambda)
}

#' Compute the HSIC statistic (unweighted)
#'
#' Biased HSIC estimator: (1/n^2) * trace(K_x_c %*% K_y_c)
#' where K_c = H K H with H = I - 1/n.
#'
#' @param Kx n x n kernel matrix for X.
#' @param Ky n x n kernel matrix for Y.
#' @return Scalar HSIC value.
#' @keywords internal
hsic_stat_cpp <- function(Kx, Ky) {
    .Call(`_kernR_hsic_stat_cpp`, Kx, Ky)
}

#' Compute the weighted HSIC statistic (for bd-HSIC)
#'
#' Weighted version
#' \deqn{\sum_{i,j} w_i w_j (K_x^c)_{ij} (K_y^c)_{ij}}{
#'       sum_(i,j) w_i * w_j * Kxc(i,j) * Kyc(i,j)}.
#'
#' @param Kx n x n kernel matrix for X.
#' @param Ky n x n kernel matrix for Y.
#' @param w Weight vector of length n.
#' @return Scalar weighted HSIC value.
#' @keywords internal
weighted_hsic_stat_cpp <- function(Kx, Ky, w) {
    .Call(`_kernR_weighted_hsic_stat_cpp`, Kx, Ky, w)
}

#' Compute the median pairwise distance (bandwidth heuristic)
#'
#' @param x Numeric matrix (n x d).
#' @return Scalar: sqrt(median of squared pairwise distances).
#' @keywords internal
median_bandwidth_cpp <- function(x) {
    .Call(`_kernR_median_bandwidth_cpp`, x)
}

#' RBF (Gaussian) kernel matrix
#'
#' K(x, y) = exp(-||x - y||^2 / (2 * bandwidth^2))
#'
#' @param x Numeric matrix (n x d).
#' @param y Numeric matrix (m x d).
#' @param bandwidth Positive scalar.
#' @return n x m kernel matrix.
#' @keywords internal
rbf_kernel_matrix_cpp <- function(x, y, bandwidth) {
    .Call(`_kernR_rbf_kernel_matrix_cpp`, x, y, bandwidth)
}

#' Matern kernel matrix
#'
#' Supports nu = 0.5, 1.5, 2.5, and Inf (RBF).
#'
#' @param x Numeric matrix (n x d).
#' @param y Numeric matrix (m x d).
#' @param bandwidth Positive scalar.
#' @param nu Smoothness parameter.
#' @return n x m kernel matrix.
#' @keywords internal
matern_kernel_matrix_cpp <- function(x, y, bandwidth, nu) {
    .Call(`_kernR_matern_kernel_matrix_cpp`, x, y, bandwidth, nu)
}

#' Linear kernel matrix
#'
#' K(x, y) = x %*% t(y)
#'
#' @param x Numeric matrix (n x d).
#' @param y Numeric matrix (m x d).
#' @return n x m kernel matrix.
#' @keywords internal
linear_kernel_matrix_cpp <- function(x, y) {
    .Call(`_kernR_linear_kernel_matrix_cpp`, x, y)
}

#' Polynomial kernel matrix
#'
#' K(x, y) = (x %*% t(y) + offset)^degree
#'
#' @param x Numeric matrix (n x d).
#' @param y Numeric matrix (m x d).
#' @param degree Integer degree.
#' @param offset Scalar offset.
#' @return n x m kernel matrix.
#' @keywords internal
polynomial_kernel_matrix_cpp <- function(x, y, degree, offset) {
    .Call(`_kernR_polynomial_kernel_matrix_cpp`, x, y, degree, offset)
}

#' Inverse multi-quadric Stein kernel matrix
#'
#' Builds the n x n Stein-kernel matrix u_p(x_i, x_j) for the IMQ base
#' kernel k(x, y) = (c^2 + ||x - y||^2)^beta under the Langevin Stein
#' operator, given the score (gradient of the log target density) evaluated
#' at each sample point.
#'
#' @param X Numeric matrix (n x d): the sample.
#' @param S Numeric matrix (n x d): the score evaluated row-wise at X.
#' @param beta Negative scalar exponent in (-1, 0).
#' @param c2 Squared offset c^2 (positive scalar).
#' @return Symmetric n x n Stein-kernel matrix.
#' @keywords internal
stein_kernel_imq_cpp <- function(X, S, beta, c2) {
    .Call(`_kernR_stein_kernel_imq_cpp`, X, S, beta, c2)
}

#' RBF Stein kernel matrix
#'
#' Builds the n x n Stein-kernel matrix u_p(x_i, x_j) for the Gaussian
#' base kernel k(x, y) = exp(-||x - y||^2 / (2 h^2)) under the Langevin
#' Stein operator, given the score evaluated at each sample point. The
#' bandwidth convention matches rbf_kernel_matrix_cpp.
#'
#' @param X Numeric matrix (n x d): the sample.
#' @param S Numeric matrix (n x d): the score evaluated row-wise at X.
#' @param h2 Squared bandwidth h^2 (positive scalar).
#' @return Symmetric n x n Stein-kernel matrix.
#' @keywords internal
stein_kernel_rbf_cpp <- function(X, S, h2) {
    .Call(`_kernR_stein_kernel_rbf_cpp`, X, S, h2)
}

#' Wild bootstrap of the kernel Stein discrepancy null
#'
#' Given the Stein-kernel matrix H, draws n_boot wild-bootstrap replicates
#' of the degenerate U-statistic null via independent Rademacher multipliers
#' \eqn{W_i \in \{-1, +1\}}: each replicate is
#' \eqn{(1 / (n (n - 1))) \sum_{i \ne j} W_i W_j H_{ij}}. The diagonal is
#' excluded to match the unbiased U-statistic. Multipliers are drawn through
#' R's RNG (R::unif_rand within Rcpp's RNGScope), so callers honour
#' set.seed().
#'
#' @param H Symmetric n x n Stein-kernel matrix.
#' @param n_boot Number of bootstrap replicates.
#' @return Vector of n_boot bootstrap KSD statistics.
#' @keywords internal
ksd_wild_bootstrap_cpp <- function(H, n_boot) {
    .Call(`_kernR_ksd_wild_bootstrap_cpp`, H, n_boot)
}

#' Compute the unbiased MMD^2 statistic
#'
#' Unbiased estimator of MMD^2:
#' \deqn{\frac{1}{n(n-1)} \sum_{i \ne j} K_{xx}(i,j) +
#'       \frac{1}{m(m-1)} \sum_{i \ne j} K_{yy}(i,j) -
#'       \frac{2}{nm} \sum_{i,j} K_{xy}(i,j)}{
#'       1/(n(n-1)) sum_(i!=j) K_xx(i,j) +
#'       1/(m(m-1)) sum_(i!=j) K_yy(i,j) -
#'       2/(nm) sum_(i,j) K_xy(i,j)}
#'
#' @param Kxx n x n kernel matrix for sample X.
#' @param Kyy m x m kernel matrix for sample Y.
#' @param Kxy n x m kernel matrix between X and Y.
#' @return Scalar unbiased MMD^2 value.
#' @keywords internal
mmd2_unbiased_cpp <- function(Kxx, Kyy, Kxy) {
    .Call(`_kernR_mmd2_unbiased_cpp`, Kxx, Kyy, Kxy)
}

#' Compute the biased MMD^2 statistic
#'
#' @param Kxx n x n kernel matrix for sample X.
#' @param Kyy m x m kernel matrix for sample Y.
#' @param Kxy n x m kernel matrix between X and Y.
#' @return Scalar biased MMD^2 value.
#' @keywords internal
mmd2_biased_cpp <- function(Kxx, Kyy, Kxy) {
    .Call(`_kernR_mmd2_biased_cpp`, Kxx, Kyy, Kxy)
}

#' Permutation HSIC: compute HSIC for many Y permutations
#'
#' Efficiently computes HSIC under permutations of the Y kernel matrix.
#' Only the row/column indices of Ky are permuted (avoiding recomputation).
#'
#' @param Kx n x n kernel matrix for X.
#' @param Ky n x n kernel matrix for Y.
#' @param n_perm Number of permutations.
#' @return Vector of n_perm HSIC values under permutation.
#' @keywords internal
permutation_hsic_cpp <- function(Kx, Ky, n_perm) {
    .Call(`_kernR_permutation_hsic_cpp`, Kx, Ky, n_perm)
}

#' Permutation MMD: compute MMD^2 for many permutations of pooled data
#'
#' Given the full (n+m) x (n+m) kernel matrix of the pooled sample,
#' permute the assignment into two groups and compute MMD^2.
#'
#' @param K_pool (n+m) x (n+m) kernel matrix.
#' @param n Size of first sample.
#' @param m Size of second sample.
#' @param n_perm Number of permutations.
#' @return Vector of n_perm MMD^2 values under permutation.
#' @keywords internal
permutation_mmd_cpp <- function(K_pool, n, m, n_perm) {
    .Call(`_kernR_permutation_mmd_cpp`, K_pool, n, m, n_perm)
}

#' Stratified permutation of indices within bins
#'
#' Given bin assignments, permute indices within each bin.
#'
#' @param bins Integer vector of bin assignments (1-indexed).
#' @param n_bins Number of bins.
#' @return Permuted index vector (0-indexed for C++).
#' @keywords internal
stratified_permute_cpp <- function(bins, n_bins) {
    .Call(`_kernR_stratified_permute_cpp`, bins, n_bins)
}

#' Permutation k-sample MMD: summed pairwise unbiased MMD^2 under joint relabel
#'
#' Given the pooled (N x N) kernel matrix of K stacked groups and their sizes,
#' draws n_perm joint relabelings of the pooled sample into the original group
#' sizes and returns, for each, the summed pairwise unbiased MMD^2 statistic
#' \eqn{\sum_{a < b} \mathrm{MMD}^2_u(a, b)}. The single shared relabeling per
#' replicate (not independent per-pair permutation) is what makes this a valid
#' k-sample null. Relabeling uses r_randperm, so callers honour set.seed().
#'
#' @param K_pool (N x N) kernel matrix of the row-stacked groups.
#' @param sizes Integer vector of the K group sizes (summing to N).
#' @param n_perm Number of permutations.
#' @return Vector of n_perm summed-pairwise MMD^2 values under the null.
#' @keywords internal
permutation_ksample_mmd_cpp <- function(K_pool, sizes, n_perm) {
    .Call(`_kernR_permutation_ksample_mmd_cpp`, K_pool, sizes, n_perm)
}

