#' HSIC-Based Distributional Sensitivity Index
#'
#' Computes HSIC-based sensitivity indices (Da Veiga, 2015) for each
#' input parameter against each output. By default returns first-order
#' indices only; `total_order = TRUE` adds the complementary total-order
#' decomposition.
#'
#' **First-order index** (always computed):
#' \deqn{S^{HSIC}_j = \frac{HSIC(X_j, Y)}{\sqrt{HSIC(X_j, X_j) \cdot HSIC(Y, Y)}}}{
#'       S_j^HSIC = HSIC(X_j, Y) / sqrt(HSIC(X_j, X_j) * HSIC(Y, Y))}
#' is the direct contribution of `X_j` to `Y` -- analogous to (but not
#' equal to) the Sobol first-order index.
#'
#' **Total-order index** (when `total_order = TRUE`):
#' \deqn{T^{HSIC}_j = 1 - \frac{HSIC(X_{\sim j}, Y)}{\sqrt{HSIC(X_{\sim j}, X_{\sim j}) \cdot HSIC(Y, Y)}}}{
#'       T_j^HSIC = 1 - HSIC(X_(-j), Y) / sqrt(HSIC(X_(-j), X_(-j)) * HSIC(Y, Y))}
#' where `X_{~j}` is the parameter design with column `j` removed. By
#' construction the difference `T_j - S_j` captures the contribution of
#' `X_j` *through interactions* with other parameters. For purely
#' additive models `T_j = S_j`; in the presence of interaction
#' `T_j > S_j`.
#'
#' Unlike variance-based Sobol indices, both versions of the
#' HSIC-Sensitivity Index capture non-linear and distributional
#' effects: a parameter that affects the variance, skewness, or tail
#' of `Y` without shifting its mean is invisible to Sobol but visible
#' to HSIC. The normalisation bounds each index to `[0, 1]`.
#'
#' Optional permutation p-values are computed for first-order indices
#' (Benjamini-Hochberg-adjusted across the grid by default).
#'
#' **Total-order uncertainty quantification (`total_order_ci = TRUE`,
#' since 0.0.0.9013).** A pair-bootstrap percentile CI on the index
#' `T_j` itself: resample `(theta, y)` pairs with replacement
#' `n_bootstrap` times, recompute `T_j` on each resample, report a
#' `ci_level` (default 95%) two-sided percentile interval. This is
#' uncertainty quantification, not a hypothesis test.
#'
#' **Total-order conditional-permutation significance test
#' (`total_order_test = "cond_perm"`, since 0.0.0.9014).** Tests
#' `H_0: X_j _||_ Y | X_{~j}` -- under the null, `X_j` adds nothing
#' beyond what is already in `X_{~j}` and `T_j` is concentrated at
#' zero. The null is generated by **conditional permutation**:
#' k-means-cluster the design points by `X_{~j}` similarity, then
#' within each cluster permute `Y`; recompute `T_j` on each permuted
#' design. p-value `= (1 + #{T_perm >= T_obs}) / (1 + B)`. The
#' `p_adjust` method applies grid-wide.
#'
#' The 0.0.0.9012 `total_order_p_value` pair-bootstrap implementation
#' was **not** this -- it sampled the empirical joint, not a
#' null-of-no-effect, and was retracted in 0.0.0.9013. The
#' 0.0.0.9014 conditional-permutation test repopulates
#' `p_value_total_order` with a properly-calibrated value; the
#' `total_order_test` flag on the result distinguishes the new mode
#' from the retracted one.
#'
#' **Power caveat (empirical calibration 2026-05-16).** Repeated-seed
#' calibration (`orchestra_calibration_20260516.R`, B = 100, N = 80)
#' confirms the cond_perm test is null-calibrated (per-parameter
#' type-I rates 0.01-0.04 at nominal alpha = 0.05) but **conservative
#' on additive designs** (rejection rate ~3% on a strong-additive
#' design where the first-order test rejects above 90%). The reason
#' is structural: on additive `Y = sum_j f_j(X_j)`, the conditional
#' permutation of `Y` within `X_{~j}` bins preserves all of
#' `X_{~j}`'s contribution and randomises only the `X_j` component
#' (which is independent of `X_{~j}`), so the permuted
#' `HSIC(X_{~j}, Y_perm)` is statistically close to the observed
#' `HSIC(X_{~j}, Y)`. Use cond_perm for **interaction detection**;
#' use the first-order permutation `p_value` (always computed when
#' `p_value = TRUE`) for **additive contributions**. The two are
#' complementary, not interchangeable.
#'
#' Total-order CIs cost `B * p * q` kernel re-evaluations on resampled
#' designs; set `n_bootstrap` accordingly. Use the CI for honest
#' uncertainty bars on the index magnitude; do not interpret it as a
#' significance verdict.
#'
#' @param theta Numeric matrix `n x p` of input draws (one row per
#'   simulator run, one column per parameter). Vectors are coerced via
#'   [as.matrix()].
#' @param y Numeric matrix `n x q` of simulator outputs. Vectors are
#'   coerced via [as.matrix()].
#' @param total_order Logical. If `TRUE`, additionally compute the
#'   total-order HSIC-Sensitivity Index via Da Veiga's complement
#'   formulation. Requires `p >= 2`. Default `FALSE` (backwards-
#'   compatible).
#' @param p_value Logical. If `TRUE` (default), compute permutation
#'   p-values and BH-adjusted p-values for *first-order* indices. Set
#'   `FALSE` to skip the permutation null. Has no effect on total-order
#'   indices (see Details).
#' @param n_permutations Integer. Permutations per HSIC test. Default
#'   `500`.
#' @param total_order_ci Logical. If `TRUE`, compute pair-bootstrap
#'   percentile CIs for the total-order indices. Requires
#'   `total_order = TRUE`. Default `FALSE` (backwards-compatible).
#'   Replaces the misleading 0.0.0.9012 `total_order_p_value` argument
#'   (removed in 0.0.0.9013; see Details).
#' @param n_bootstrap Integer. Pair-bootstrap resamples used for the
#'   total-order CI. Default `200`. Only consulted when
#'   `total_order_ci = TRUE`.
#' @param ci_level Numeric in `(0, 1)`. Two-sided percentile CI level
#'   for the total-order bootstrap. Default `0.95`. Only consulted
#'   when `total_order_ci = TRUE`.
#' @param total_order_test Character. `"none"` (default; backwards-
#'   compatible) or `"cond_perm"` (since 0.0.0.9014). The latter
#'   activates a conditional-permutation test for
#'   `H_0: X_j _||_ Y | X_{~j}` and populates `p_value_total_order` and
#'   `p_value_total_order_adjusted`. Requires `total_order = TRUE`.
#'   Different from (and replaces) the retracted 0.0.0.9012
#'   pair-bootstrap method.
#' @param n_clusters_cp Integer or `"auto"`. Number of conditioning
#'   bins for the conditional-permutation test (k-means on
#'   `X_{~j}`). `"auto"` chooses `min(floor(n / 5), 20)`. Only
#'   consulted when `total_order_test = "cond_perm"`.
#' @param total_order_p_value Defunct as of 0.0.0.9013. Passing any
#'   non-`NULL` value errors with a pointer to `total_order_test`
#'   and `total_order_ci`.
#' @param p_adjust Character. Across-grid p-value adjustment method
#'   passed to [stats::p.adjust()]. Default `"BH"`.
#' @param kernel_theta A [kernel_spec()] for parameter columns. Default
#'   RBF with median heuristic. Used for both first-order (per-column)
#'   and total-order (per `X_{~j}` subset).
#' @param kernel_y A [kernel_spec()] for output columns. Default RBF
#'   with per-column median heuristic.
#' @param seed Integer or `NULL`. Random seed for reproducibility.
#'
#' @return An object of class `"hsic_sensitivity"` with components:
#'   \describe{
#'     \item{index}{`p x q` matrix of first-order HSIC-Sensitivity Indices
#'       in `[0, 1]`.}
#'     \item{statistic}{`p x q` matrix of raw first-order HSIC statistics.}
#'     \item{p_value}{`p x q` matrix of raw permutation p-values
#'       (first-order), or `NULL` if `p_value = FALSE`.}
#'     \item{p_value_adjusted}{`p x q` matrix of adjusted p-values
#'       (first-order), or `NULL`.}
#'     \item{index_total_order}{`p x q` matrix of total-order indices,
#'       or `NULL` when `total_order = FALSE`.}
#'     \item{statistic_total_order}{`p x q` matrix of HSIC(`X_{~j}`,
#'       `Y_k`) statistics, or `NULL`.}
#'     \item{total_order}{Logical flag: was total-order requested?}
#'     \item{total_index}{Length-`p` vector: per-parameter maximum
#'       *first-order* index across outputs (used for ranking; kept
#'       under this historical name for backwards compatibility).}
#'     \item{rank}{Parameter indices ordered by descending
#'       `total_index`.}
#'     \item{n, n_permutations, param_names, output_names, p_adjust}{Metadata.}
#'     \item{call}{The matched call.}
#'   }
#'
#' @references
#' Da Veiga, S. (2015). Global sensitivity analysis with dependence
#' measures. *Journal of Statistical Computation and Simulation*,
#' 85(7), 1283-1305.
#'
#' Gretton, A., Bousquet, O., Smola, A., & Scholkopf, B. (2005).
#' Measuring statistical dependence with Hilbert-Schmidt norms.
#' *ALT*, 63-77.
#'
#' @examples
#' \donttest{
#' set.seed(1)
#' n <- 80L
#' theta <- matrix(stats::runif(n * 3L), nrow = n,
#'                 dimnames = list(NULL, c("active", "weak", "inert")))
#' y <- 2 * theta[, "active"] +
#'      0.5 * theta[, "weak"] +
#'      stats::rnorm(n, sd = 0.1)
#' fit <- hsic_sensitivity(theta, y, total_order = TRUE,
#'                         n_permutations = 199L, seed = 1L)
#' fit
#' }
#'
#' @seealso [hsic_identifiability()], [hsic_test()]
#' @family sensitivity and identifiability
#' @export
hsic_sensitivity <- function(theta, y,
                             total_order = FALSE,
                             p_value = TRUE,
                             n_permutations = 500L,
                             total_order_ci = FALSE,
                             n_bootstrap = 200L,
                             ci_level = 0.95,
                             total_order_test = c("none", "cond_perm"),
                             n_clusters_cp = "auto",
                             p_adjust = c("BH", "holm", "hochberg",
                                          "bonferroni", "BY", "fdr",
                                          "none"),
                             kernel_theta = kernel_spec(),
                             kernel_y = kernel_spec(),
                             seed = NULL,
                             total_order_p_value = NULL) {
  cl <- match.call()
  p_adjust <- match.arg(p_adjust)
  total_order_test <- match.arg(total_order_test)
  if (!is.null(total_order_p_value)) {
    stop(
      "`total_order_p_value` is defunct since kernR 0.0.0.9013. The ",
      "0.0.0.9012 implementation was not null-calibrated (see ",
      "?hsic_sensitivity Details). For a CI on the index, use ",
      "`total_order_ci = TRUE`. For a null-calibrated significance ",
      "test against H_0: X_j _||_ Y | X_{~j}, use ",
      "`total_order_test = \"cond_perm\"` (0.0.0.9014+).",
      call. = FALSE
    )
  }
  if (isTRUE(total_order_ci) && !isTRUE(total_order)) {
    stop("`total_order_ci = TRUE` requires `total_order = TRUE`.",
         call. = FALSE)
  }
  if (!identical(total_order_test, "none") && !isTRUE(total_order)) {
    stop("`total_order_test = \"", total_order_test,
         "\"` requires `total_order = TRUE`.", call. = FALSE)
  }
  n_bootstrap <- as.integer(n_bootstrap)
  if (length(n_bootstrap) != 1L || is.na(n_bootstrap) ||
      n_bootstrap < 1L) {
    stop("`n_bootstrap` must be a positive integer.", call. = FALSE)
  }
  if (length(ci_level) != 1L || is.na(ci_level) ||
      ci_level <= 0 || ci_level >= 1) {
    stop("`ci_level` must be a single numeric in (0, 1).", call. = FALSE)
  }

  theta <- as.matrix(theta)
  y <- as.matrix(y)
  n <- nrow(theta)

  if (nrow(y) != n) {
    stop("`theta` and `y` must have the same number of rows.", call. = FALSE)
  }
  if (n < 10L) {
    stop("At least 10 observations (design points) are required.",
         call. = FALSE)
  }
  n_permutations <- as.integer(n_permutations)
  if (length(n_permutations) != 1L || is.na(n_permutations) ||
      n_permutations < 1L) {
    stop("`n_permutations` must be a positive integer.", call. = FALSE)
  }

  p <- ncol(theta)
  q <- ncol(y)
  if (isTRUE(total_order) && p < 2L) {
    stop("`total_order = TRUE` requires p >= 2 parameters.", call. = FALSE)
  }

  param_names <- colnames(theta)
  if (is.null(param_names)) param_names <- paste0("theta", seq_len(p))
  output_names <- colnames(y)
  if (is.null(output_names)) output_names <- paste0("y", seq_len(q))

  if (!is.null(seed)) set.seed(seed)

  # Per-column kernel matrices (reused across the first-order grid).
  Kx_list <- vector("list", p)
  Kxx_diag <- numeric(p)
  for (j in seq_len(p)) {
    xj <- theta[, j, drop = FALSE]
    kj <- resolve_bandwidth(kernel_theta, xj)
    Kx_list[[j]] <- kernel_matrix(xj, kernel = kj)
    Kxx_diag[j]  <- hsic_stat_cpp(Kx_list[[j]], Kx_list[[j]])
  }
  Ky_list <- vector("list", q)
  Kyy_diag <- numeric(q)
  for (k in seq_len(q)) {
    yk <- y[, k, drop = FALSE]
    kk <- resolve_bandwidth(kernel_y, yk)
    Ky_list[[k]] <- kernel_matrix(yk, kernel = kk)
    Kyy_diag[k]  <- hsic_stat_cpp(Ky_list[[k]], Ky_list[[k]])
  }

  # ---- First-order indices ----
  stat_mat  <- matrix(NA_real_, p, q,
                      dimnames = list(param_names, output_names))
  index_mat <- stat_mat
  pval_mat  <- if (p_value) stat_mat else NULL

  for (j in seq_len(p)) {
    for (k in seq_len(q)) {
      hsic_xy <- hsic_stat_cpp(Kx_list[[j]], Ky_list[[k]])
      stat_mat[j, k] <- hsic_xy
      denom <- sqrt(Kxx_diag[j] * Kyy_diag[k])
      index_mat[j, k] <- if (denom > 0) hsic_xy / denom else 0
      if (p_value) {
        nd <- permutation_hsic_cpp(
          Kx_list[[j]], Ky_list[[k]], n_permutations
        )
        pval_mat[j, k] <- (1 + sum(nd >= hsic_xy)) / (1 + n_permutations)
      }
    }
  }
  index_mat[index_mat < 0] <- 0
  index_mat[index_mat > 1] <- 1

  pval_adj <- if (is.null(pval_mat) || p_adjust == "none") {
    pval_mat
  } else {
    matrix(stats::p.adjust(as.vector(pval_mat), method = p_adjust),
           nrow = p, ncol = q,
           dimnames = dimnames(pval_mat))
  }

  # ---- Total-order indices (Da Veiga complement) ----
  if (isTRUE(total_order)) {
    index_total <- matrix(NA_real_, p, q,
                          dimnames = list(param_names, output_names))
    stat_total  <- index_total
    for (j in seq_len(p)) {
      theta_minus_j <- theta[, -j, drop = FALSE]
      kj <- resolve_bandwidth(kernel_theta, theta_minus_j)
      K_minus_j <- kernel_matrix(theta_minus_j, kernel = kj)
      Kxx_minus_j <- hsic_stat_cpp(K_minus_j, K_minus_j)
      for (k in seq_len(q)) {
        hsic_xy <- hsic_stat_cpp(K_minus_j, Ky_list[[k]])
        stat_total[j, k] <- hsic_xy
        denom <- sqrt(Kxx_minus_j * Kyy_diag[k])
        complement <- if (denom > 0) hsic_xy / denom else 0
        index_total[j, k] <- 1 - complement
      }
    }
    index_total[index_total < 0] <- 0
    index_total[index_total > 1] <- 1
  } else {
    index_total <- NULL
    stat_total  <- NULL
  }

  # ---- Conditional-permutation significance test (0.0.0.9014) ----
  # H_0: X_j _||_ Y | X_{~j}. Cluster X_{~j} into n_clusters_cp bins by
  # k-means; within each bin, permute y; recompute T_j. p-value =
  # (1 + #{T_perm >= T_obs}) / (1 + n_permutations). Properly
  # null-calibrated (replaces the 0.0.0.9012 retracted pair-bootstrap
  # claim).
  pval_total       <- NULL
  pval_total_adj   <- NULL
  if (identical(total_order_test, "cond_perm")) {
    if (identical(n_clusters_cp, "auto")) {
      n_clusters_cp_eff <- max(2L, min(floor(n / 5L), 20L))
    } else {
      n_clusters_cp_eff <- as.integer(n_clusters_cp)
    }
    pval_total <- matrix(NA_real_, p, q,
                         dimnames = list(param_names, output_names))
    for (j in seq_len(p)) {
      theta_minus_j <- theta[, -j, drop = FALSE]
      # k-means bins on X_{~j}. Suppress kmeans's converge-warnings
      # on small n; we don't care if a few iterations dropped out.
      bins <- suppressWarnings(
        stats::kmeans(theta_minus_j,
                      centers = min(n_clusters_cp_eff, n - 1L),
                      nstart = 3L, iter.max = 50L)$cluster
      )
      bin_lvls <- unique(bins)
      kj <- resolve_bandwidth(kernel_theta, theta_minus_j)
      K_minus_j <- kernel_matrix(theta_minus_j, kernel = kj)
      Kxx_minus_j <- hsic_stat_cpp(K_minus_j, K_minus_j)
      for (k in seq_len(q)) {
        denom <- sqrt(Kxx_minus_j * Kyy_diag[k])
        if (denom <= 0) {
          pval_total[j, k] <- 1
          next
        }
        t_obs <- 1 - hsic_stat_cpp(K_minus_j, Ky_list[[k]]) / denom
        t_perm <- numeric(n_permutations)
        for (b in seq_len(n_permutations)) {
          perm_idx <- seq_len(n)
          for (lv in bin_lvls) {
            in_bin <- which(bins == lv)
            if (length(in_bin) > 1L) {
              perm_idx[in_bin] <- sample(in_bin)
            }
          }
          y_perm <- y[perm_idx, k, drop = FALSE]
          kk_b <- resolve_bandwidth(kernel_y, y_perm)
          Ky_b <- kernel_matrix(y_perm, kernel = kk_b)
          hyy_b <- hsic_stat_cpp(Ky_b, Ky_b)
          denom_b <- sqrt(Kxx_minus_j * hyy_b)
          if (denom_b <= 0) {
            t_perm[b] <- 0
          } else {
            t_perm[b] <- 1 -
              hsic_stat_cpp(K_minus_j, Ky_b) / denom_b
          }
        }
        pval_total[j, k] <- (1 + sum(t_perm >= t_obs)) /
                            (1 + n_permutations)
      }
    }
    pval_total_adj <- if (p_adjust == "none") {
      pval_total
    } else {
      matrix(stats::p.adjust(as.vector(pval_total), method = p_adjust),
             nrow = p, ncol = q, dimnames = dimnames(pval_total))
    }
  }

  # ---- Pair-bootstrap percentile CI for total-order indices ----
  # The bootstrap is over (theta, y) pairs with replacement, giving a
  # percentile CI on the index itself (NOT a null-calibrated p-value
  # for H_0: T_j = 0; see Details, and the 2026-05-16 critical-review
  # retraction in NEWS 0.0.0.9013).
  ci_total_lower  <- NULL
  ci_total_upper  <- NULL
  if (isTRUE(total_order_ci)) {
    ci_total_lower <- matrix(NA_real_, p, q,
                             dimnames = list(param_names, output_names))
    ci_total_upper <- ci_total_lower
    ci_alpha       <- (1 - ci_level) / 2
    for (j in seq_len(p)) {
      for (k in seq_len(q)) {
        t_boot <- numeric(n_bootstrap)
        for (b in seq_len(n_bootstrap)) {
          idx <- sample.int(n, n, replace = TRUE)
          theta_mj_b <- theta[idx, -j, drop = FALSE]
          y_k_b      <- y[idx, k, drop = FALSE]
          kj_b <- resolve_bandwidth(kernel_theta, theta_mj_b)
          kk_b <- resolve_bandwidth(kernel_y, y_k_b)
          Kx_b <- kernel_matrix(theta_mj_b, kernel = kj_b)
          Ky_b <- kernel_matrix(y_k_b,      kernel = kk_b)
          hxx <- hsic_stat_cpp(Kx_b, Kx_b)
          hyy <- hsic_stat_cpp(Ky_b, Ky_b)
          hxy <- hsic_stat_cpp(Kx_b, Ky_b)
          denom_b <- sqrt(hxx * hyy)
          comp_b  <- if (denom_b > 0) hxy / denom_b else 0
          t_boot[b] <- max(0, min(1, 1 - comp_b))
        }
        ci_total_lower[j, k] <- stats::quantile(t_boot, ci_alpha,
                                                names = FALSE)
        ci_total_upper[j, k] <- stats::quantile(t_boot, 1 - ci_alpha,
                                                names = FALSE)
      }
    }
  }

  total_index <- apply(index_mat, 1L, max)
  rank <- order(total_index, decreasing = TRUE)

  structure(
    list(
      index                 = index_mat,
      statistic             = stat_mat,
      p_value               = pval_mat,
      p_value_adjusted      = pval_adj,
      index_total_order     = index_total,
      statistic_total_order = stat_total,
      ci_total_order_lower  = ci_total_lower,
      ci_total_order_upper  = ci_total_upper,
      ci_level              = ci_level,
      n_bootstrap           = if (isTRUE(total_order_ci))
                                n_bootstrap else NA_integer_,
      p_value_total_order   = pval_total,
      p_value_total_order_adjusted = pval_total_adj,
      total_order_test      = total_order_test,
      total_order           = isTRUE(total_order),
      total_order_ci        = isTRUE(total_order_ci),
      total_index           = total_index,
      rank                  = rank,
      n                     = n,
      n_permutations        = n_permutations,
      p_adjust              = p_adjust,
      param_names           = param_names,
      output_names          = output_names,
      call                  = cl
    ),
    class = "hsic_sensitivity"
  )
}
